apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-express-apiserver
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        # configMapRef refers to a ConfigMap with GVK/schema to search for (i.e., PlacementDecision)
        #   for us - PlacementDecision.cluster.open-cluster-management.io/v1
        configMapRef: acm-placement
        # labelSelector selects a specific instance of GVK PlacementDecision
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: nodejs-express-apiserver-placement
        requeueAfterSeconds: 60
  template:
    metadata:
      name: nodejs-express-apiserver-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      sources:
        - repositoryType: git
          repoURL: https://github.com/joshgav/nodejs-express-apiserver.git
          targetRevision: main
          path: deploy/openshift
          kustomize: {}
      destination:
        namespace: nodejs-express-apiserver
        server: "{{server}}"
      syncPolicy:
        automated:
          enabled: true
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nodejs-express-apiserver-placement
  namespace: openshift-gitops
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - global