apiVersion: v1
kind: Service
metadata:
  name: nodejs-apiserver
  namespace: nodejs-apiserver
spec:
  selector:
    app: nodejs-apiserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http