pipeline:
  name: first
  identifier: first
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubjoshgav
        repoName: nodejs-express-apiserver
        build: <+input>
  stages:
    - stage:
        name: npm-install
        identifier: npminstall
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: ContainerBuildAndPush
                  identifier: ContainerBuildAndPush
                  spec:
                    connectorRef: quay
                    repo: quay.io/joshgav/nodejs-express-apiserver
                    tags:
                      - latest
                    caching: true
