apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-express-apiserver
  namespace: nodejs-apiserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: nodejs-express-apiserver-app
  endpoints:
  - port: 8080-tcp
    interval: 5s
    path: /metrics
    scheme: http